[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Libraries required for WebSocket and JSON
lib_deps =
    Links2004/WebSockets@^2.3.7
    ArduinoJson@^6.21.2

